[build]
  publish = "dist"
  command = "bash ./netlify-build-script.sh"
  ignore = 'bash -c "[[ "$(date -d "5 minutes ago" +%s)" -gt "$(cat last_build_timestamp.txt 2>/dev/null || echo 0)" ]] && exit 1 || exit 0"'
  

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

