[build]
  publish = "dist"
  # command = "npm install && npm run build"
  command = "NODE_OPTIONS=--max-old-space-size=8192 npm install && NODE_OPTIONS=--max-old-space-size=8192 npm run build"
  ignore = "exit 0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

