[build]
  publish = "dist"
  # command = "npm install && npm run build"
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm install && npm run build"
  ignore = "exit 0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

